### ISSUE TITLE
is there python interface?

### ISSUE THREAD

**Issue by SeekPoint** [3F/regXwild#6]

**Comment by 3F** [comment]
Nothing special for python; at least for today.

For python you need **ctypes** use: https://docs.python.org/3/library/ctypes.html#module-ctypes

And since regXwild exports the following functions (C-mangling): https://github.com/3F/regXwild/blob/master/regXwild/regXwildAPI.h

For example, for:

```c
bool searchEssC(const TCHAR* data, const TCHAR* filter, bool ignoreCase);
```

and for Unicode module (latest versions also distributed with MultiByte) it can be as below ~

```python
import ctypes
regXwild = ctypes.cdll.LoadLibrary('regXwild.dll')

wstr  = ctypes.c_wchar_p("TV_[11_of_24]");
icase = ctypes.c_bool(0)

regXwild.searchEssC(wstr, ctypes.c_wchar_p("1?_*24"), icase)
```

Let me know if you still have some problems.

**Comment by SeekPoint** [comment]
Great
